services:
  db:
    ports:
      - 5433:5433
    command: ['postgres', '-c', 'max_connections=500', '-c', 'log_statement=all', '-c', 'port=5433']
  redis:
    ports:
      - 6378 # hide redis from the warehouse
  mailhog:
    image: cd2team/mailhog
