version: '3.8'

services:
  db:
    # image: joaoams/postgis-arm64
    image: gangstead/postgis:13-3.1-arm
    ports:
      - 5432:5432
    command: ['postgres', '-c', 'max_connections=500', '-c', 'log_statement=all', '-c', 'port=5432']
  mailhog:
    image: cd2team/mailhog
